name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Setup Terragrunt
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.12/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

    - name: Initialize and apply VPC
      working-directory: ./vpc
      run: |
        terragrunt init
        terragrunt plan -out=tfplan
        terragrunt apply -auto-approve tfplan

    - name: Initialize and apply EKS
      working-directory: ./eks
      run: |
        terragrunt init
        terragrunt plan -out=tfplan
        terragrunt apply -auto-approve tfplan

    - name: Initialize and apply EC2
      working-directory: ./ec2
      run: |
        terragrunt init
        terragrunt plan -out=tfplan
        terragrunt apply -auto-approve tfplan