name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Initialize and plan VPC
      working-directory: ./vpc
      run: |
        terraform init
        terraform plan -input=false -out=tfplan

    - name: Apply VPC
      working-directory: ./vpc
      run: terraform apply -input=false -auto-approve tfplan

    - name: Initialize and plan EKS
      working-directory: ./eks
      run: |
        terraform init
        terraform plan -input=false -out=tfplan

    - name: Apply EKS
      working-directory: ./eks
      run: terraform apply -input=false -auto-approve tfplan

    - name: Initialize and plan EC2
      working-directory: ./ec2
      run: |
        terraform init
        terraform plan -input=false -out=tfplan

    - name: Apply EC2
      working-directory: ./ec2
      run: terraform apply -input=false -auto-approve tfplan