name: Terragrunt

on:
  push:
    branches:
      - main

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_CLI_PATH: /home/runner/work/_temp/26b7339b-764f-40d0-be9e-4f0f25abab1a

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Setup Terragrunt
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.12/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

    - name: Initialize and plan VPC
      working-directory: ./Terraform/Terragrunt/vpc
      run: |
        terragrunt init
        terragrunt plan -input=false 
    #-out=tfplan

    - name: Apply VPC
      working-directory: ./Terraform/Terragrunt/vpc
      run: terragrunt apply -input=false 
      #-auto-approve tfplan

      
    - name: Initialize and plan EC2
      working-directory: ./Terraform/Terragrunt/ec2
      run: |
        terragrunt init
        terragrunt plan -input=false 
        #-out=tfplan

    - name: Apply EC2
      working-directory: ./Terraform/Terragrunt/ec2
      run: terragrunt apply -input=false 
        #-auto-approve tfplan

    - name: Initialize and plan EKS
      working-directory: ./Terraform/Terragrunt/eks
      run: |
        terragrunt init
        terragrunt plan -input=false 
    #-out=tfplan

    - name: Apply EKS
      working-directory: ./Terraform/Terragrunt/eks
      run: terragrunt apply -input=false 
    #-auto-approve tfplan
